//$file${./watch/src::HSM.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: _watch.qm
// File:  ${./watch/src::HSM.c}
//
// This code has been generated by QM 6.2.3 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// Copyright (c) 2005 Quantum Leaps, LLC
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for licensees
// interested in retaining the proprietary status of the generated code.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${./watch/src::HSM.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpc.h"
#include "bsp.h"

// DECLARA OS MÉTODOS
//$declare${AOs::Watch} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Watch} ..............................................................
typedef struct Watch {
// protected:
    QActive super;

// private:
    QTimeEvt timeEvt0;

// public:
} Watch;

extern Watch Watch_instance;

// protected:
static QState Watch_initial(Watch * const me, void const * const par);
static QState Watch_active(Watch * const me, QEvt const * const e);
static QState Watch_timekeeping(Watch * const me, QEvt const * const e);
// SHOWS FACE
static QState Watch_countdown_FACE(Watch * const me, QEvt const * const e);
// SHOWS CONFIG
static QState Watch_countdown_config(Watch * const me, QEvt const * const e);
// SHOWS FACE
static QState Watch_time_date_FACE(Watch * const me, QEvt const * const e);
// SHOWS CONFIG
static QState Watch_time_date_config(Watch * const me, QEvt const * const e);
static QState Watch_heart_rate(Watch * const me, QEvt const * const e);
// SHOWS FACE
static QState Watch_settings_FACE(Watch * const me, QEvt const * const e);
// SHOW SETTINGS
static QState Watch_settings(Watch * const me, QEvt const * const e);
static QState Watch_HR_FACE(Watch * const me, QEvt const * const e);
static QState Watch_HR_measuring(Watch * const me, QEvt const * const e);
//$enddecl${AOs::Watch} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

// CRIA O OBJETO
//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::AO_Watch} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::AO_Watch} ...........................................................
QActive* const AO_Watch = &Watch_instance.super;
//$enddef${AOs::AO_Watch} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define${AOs::Watch_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Watch_ctor} .........................................................
void Watch_ctor(void) {
    Watch *me = &Watch_instance;
    QActive_ctor(&me->super, Q_STATE_CAST(&Watch_initial));
}
//$enddef${AOs::Watch_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

// CRIA OS
//$define${AOs::Watch} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Watch} ..............................................................
Watch Watch_instance;

//${AOs::Watch::SM} ..........................................................
static QState Watch_initial(Watch * const me, void const * const par) {
    //${AOs::Watch::SM::initial}
    (void)par; // unused parameter
    QActive_subscribe(&me->super, ENTER_SIG);
    QActive_subscribe(&me->super, MODE_SIG);
    QActive_subscribe(&me->super, BACK_SIG);
    QActive_subscribe(&me->super, TOGGLE_SIG);
    return Q_TRAN(&Watch_active);
}

//${AOs::Watch::SM::active} ..................................................
static QState Watch_active(Watch * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Watch::SM::active}
        case Q_ENTRY_SIG: {
            printf("->active-entry");
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Watch::SM::active::initial}
        case Q_INIT_SIG: {
            status_ = Q_TRAN(&Watch_timekeeping);
            break;
        }
        //${AOs::Watch::SM::active::TICK}
        case TICK_SIG: {
            // SOMO O TEMPO AQUI, é JUSTO ATUALIZAR TAMBÉM
            printf("->tick-evt");
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${AOs::Watch::SM::active::timekeeping} .....................................
static QState Watch_timekeeping(Watch * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Watch::SM::active::timekeeping}
        case Q_ENTRY_SIG: {
            printf("->timekeeping-entry");
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Watch::SM::active::timekeeping}
        case Q_EXIT_SIG: {
            printf("->timekeeping-exit");
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Watch::SM::active::timekeeping::MODE}
        case MODE_SIG: {
            status_ = Q_TRAN(&Watch_countdown_FACE);
            break;
        }
        default: {
            status_ = Q_SUPER(&Watch_active);
            break;
        }
    }
    return status_;
}

//${AOs::Watch::SM::active::countdown_FACE} ..................................
static QState Watch_countdown_FACE(Watch * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Watch::SM::active::countdown_FACE}
        case Q_ENTRY_SIG: {
            printf("->countdown-entry");
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Watch::SM::active::countdown_FACE}
        case Q_EXIT_SIG: {
            printf("->countdown-exit");
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Watch::SM::active::countdown_FACE::TOGGLE}
        case TOGGLE_SIG: {
            // STARTA OU PARA O CRONOMETRO
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Watch::SM::active::countdown_FACE::ENTER}
        case ENTER_SIG: {
            status_ = Q_TRAN(&Watch_countdown_config);
            break;
        }
        //${AOs::Watch::SM::active::countdown_FACE::MODE}
        case MODE_SIG: {
            status_ = Q_TRAN(&Watch_heart_rate);
            break;
        }
        //${AOs::Watch::SM::active::countdown_FACE::TIMEOUT}
        case TIMEOUT_SIG: {
            status_ = Q_TRAN(&Watch_timekeeping);
            break;
        }
        default: {
            status_ = Q_SUPER(&Watch_active);
            break;
        }
    }
    return status_;
}

//${AOs::Watch::SM::active::countdown_FACE::countdown_config} ................
static QState Watch_countdown_config(Watch * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Watch::SM::active::countdown_FACE::countdown_config}
        case Q_ENTRY_SIG: {
            printf("->countdown_config-entry");
            //blink(me->time[sel_field])
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Watch::SM::active::countdown_FACE::countdown_config}
        case Q_EXIT_SIG: {
            printf("->countdown_config-exit");
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Watch::SM::active::countdown_FACE::countdown_config::MODE}
        case MODE_SIG: {
            // AFIRMA E AVANÇA CAMPO
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Watch::SM::active::countdown_FACE::countdown_config::TOGGLE}
        case TOGGLE_SIG: {
            // AUMENTA +1 O VALOR DO CAMPO HORA, MINUTO OU SEGUNDO

            // OBS -> DEFINIDO PELA VARIÁVEL DE CONTROLE DE MODE.
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Watch::SM::active::countdown_FACE::countdown_config::ENTER}
        case ENTER_SIG: {
            status_ = Q_TRAN(&Watch_countdown_FACE);
            break;
        }
        default: {
            status_ = Q_SUPER(&Watch_countdown_FACE);
            break;
        }
    }
    return status_;
}

//${AOs::Watch::SM::active::time_date_FACE} ..................................
static QState Watch_time_date_FACE(Watch * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Watch::SM::active::time_date_FACE}
        case Q_ENTRY_SIG: {
            printf("->time_data-entry");
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Watch::SM::active::time_date_FACE}
        case Q_EXIT_SIG: {
            printf("->time_data-exit");
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Watch::SM::active::time_date_FACE::ENTER}
        case ENTER_SIG: {
            status_ = Q_TRAN(&Watch_time_date_config);
            break;
        }
        //${AOs::Watch::SM::active::time_date_FACE::TIMEOUT}
        case TIMEOUT_SIG: {
            status_ = Q_TRAN(&Watch_timekeeping);
            break;
        }
        //${AOs::Watch::SM::active::time_date_FACE::MODE}
        case MODE_SIG: {
            status_ = Q_TRAN(&Watch_settings_FACE);
            break;
        }
        default: {
            status_ = Q_SUPER(&Watch_active);
            break;
        }
    }
    return status_;
}

//${AOs::Watch::SM::active::time_date_FACE::time_date_config} ................
static QState Watch_time_date_config(Watch * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Watch::SM::active::time_date_FACE::time_date_config}
        case Q_ENTRY_SIG: {
            printf("->time_date_config-entry");
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Watch::SM::active::time_date_FACE::time_date_config}
        case Q_EXIT_SIG: {
            printf("->time_date_config-exit");
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Watch::SM::active::time_date_FACE::time_date_config::MODE}
        case MODE_SIG: {
            // AFIRMA E AVANÇA CAMPO
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Watch::SM::active::time_date_FACE::time_date_config::TOGGLE}
        case TOGGLE_SIG: {
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Watch::SM::active::time_date_FACE::time_date_config::ENTER}
        case ENTER_SIG: {
            status_ = Q_TRAN(&Watch_time_date_FACE);
            break;
        }
        default: {
            status_ = Q_SUPER(&Watch_time_date_FACE);
            break;
        }
    }
    return status_;
}

//${AOs::Watch::SM::active::heart_rate} ......................................
static QState Watch_heart_rate(Watch * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Watch::SM::active::heart_rate}
        case Q_ENTRY_SIG: {
            printf("->heartrate-entry");
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Watch::SM::active::heart_rate}
        case Q_EXIT_SIG: {
            printf("->heartrate-exit");
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Watch::SM::active::heart_rate::MODE}
        case MODE_SIG: {
            status_ = Q_TRAN(&Watch_time_date_FACE);
            break;
        }
        //${AOs::Watch::SM::active::heart_rate::TIMEOUT}
        case TIMEOUT_SIG: {
            status_ = Q_TRAN(&Watch_timekeeping);
            break;
        }
        default: {
            status_ = Q_SUPER(&Watch_active);
            break;
        }
    }
    return status_;
}

//${AOs::Watch::SM::active::settings_FACE} ...................................
static QState Watch_settings_FACE(Watch * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Watch::SM::active::settings_FACE}
        case Q_ENTRY_SIG: {
            printf("->settings-entry");
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Watch::SM::active::settings_FACE}
        case Q_EXIT_SIG: {
            printf("->settings-exit");
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Watch::SM::active::settings_FACE::ENTER}
        case ENTER_SIG: {
            status_ = Q_TRAN(&Watch_settings);
            break;
        }
        //${AOs::Watch::SM::active::settings_FACE::MODE}
        case MODE_SIG: {
            status_ = Q_TRAN(&Watch_timekeeping);
            break;
        }
        default: {
            status_ = Q_SUPER(&Watch_active);
            break;
        }
    }
    return status_;
}

//${AOs::Watch::SM::active::settings_FACE::settings} .........................
static QState Watch_settings(Watch * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Watch::SM::active::settings_FACE::settings}
        case Q_ENTRY_SIG: {
            printf("->settings_config-entry");
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Watch::SM::active::settings_FACE::settings}
        case Q_EXIT_SIG: {
            printf("->settings_config-exit");
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Watch::SM::active::settings_FACE::settings::ENTER}
        case ENTER_SIG: {
            status_ = Q_TRAN(&Watch_settings_FACE);
            break;
        }
        //${AOs::Watch::SM::active::settings_FACE::settings::TOGGLE}
        case TOGGLE_SIG: {
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Watch::SM::active::settings_FACE::settings::MODE}
        case MODE_SIG: {
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&Watch_settings_FACE);
            break;
        }
    }
    return status_;
}

//${AOs::Watch::SM::HR_FACE} .................................................
static QState Watch_HR_FACE(Watch * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Watch::SM::HR_FACE}
        case Q_ENTRY_SIG: {
            //entry_face(HR_FACE);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Watch::SM::HR_FACE::ENTER}
        case ENTER_SIG: {
            status_ = Q_TRAN(&Watch_HR_measuring);
            break;
        }
        //${AOs::Watch::SM::HR_FACE::TIMEOUT}
        case TIMEOUT_SIG: {
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${AOs::Watch::SM::HR_FACE::HR_measuring} ...................................
static QState Watch_HR_measuring(Watch * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = Q_SUPER(&Watch_HR_FACE);
            break;
        }
    }
    return status_;
}
//$enddef${AOs::Watch} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
