//$file${./watch/src::notification.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: _watch.qm
// File:  ${./watch/src::notification.c}
//
// This code has been generated by QM 6.2.3 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// Copyright (c) 2005 Quantum Leaps, LLC
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for licensees
// interested in retaining the proprietary status of the generated code.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${./watch/src::notification.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpc.h"
#include "bsp.h"
#include "app.h"

// DECLARA OS MÉTODOS
//$declare${Components::NotificationMgr} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Components::NotificationMgr} .............................................
typedef struct NotificationMgr {
// protected:
    QActive super;

// public:

// private:
    QTimeEvt alertTimer;
} NotificationMgr;

extern NotificationMgr NotificationMgr_inst;

// protected:
static QState NotificationMgr_initial(NotificationMgr * const me, void const * const par);
static QState NotificationMgr_idle(NotificationMgr * const me, QEvt const * const e);
static QState NotificationMgr_alerting(NotificationMgr * const me, QEvt const * const e);
//$enddecl${Components::NotificationMgr} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

// CRIA O OBJETO
//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${App::AO_NotificationMgr} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${App::AO_NotificationMgr} .................................................
QActive* const AO_NotificationMgr = Q_ACTIVE_UPCAST(&NotificationMgr_inst);
//$enddef${App::AO_NotificationMgr} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define${App::NotificationMgr_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${App::NotificationMgr_ctor} ...............................................
void NotificationMgr_ctor(void) {
    NotificationMgr *me = &NotificationMgr_inst;
    QActive_ctor(&me->super, Q_STATE_CAST(&NotificationMgr_initial));

    QTimeEvt_ctorX(&me->alertTimer, &me->super, ALARM_TIMEOUT_SIG, 0U);
}
//$enddef${App::NotificationMgr_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

// CRIA OS
//$define${Components::NotificationMgr} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Components::NotificationMgr} .............................................
NotificationMgr NotificationMgr_inst;

//${Components::NotificationMgr::SM} .........................................
static QState NotificationMgr_initial(NotificationMgr * const me, void const * const par) {
    //${Components::NotificationMgr::SM::initial}
    QActive_subscribe(&me->super, MEDICINE_ALARM_SIG);
    QActive_subscribe(&me->super, SNOOZE_SIG);
    QActive_subscribe(&me->super, DISMISS_SIG);
    return Q_TRAN(&NotificationMgr_idle);
}

//${Components::NotificationMgr::SM::idle} ...................................
static QState NotificationMgr_idle(NotificationMgr * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${Components::NotificationMgr::SM::idle::MEDICINE_ALARM}
        case MEDICINE_ALARM_SIG: {
            status_ = Q_TRAN(&NotificationMgr_alerting);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${Components::NotificationMgr::SM::alerting} ...............................
static QState NotificationMgr_alerting(NotificationMgr * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${Components::NotificationMgr::SM::alerting}
        case Q_ENTRY_SIG: {
            QTimeEvt_armX(&me->alertTimer, 10000U, 0U);
            status_ = Q_HANDLED();
            break;
        }
        //${Components::NotificationMgr::SM::alerting}
        case Q_EXIT_SIG: {
            QTimeEvt_disarm(&me->alertTimer);
            status_ = Q_HANDLED();
            break;
        }
        //${Components::NotificationMgr::SM::alerting::DISMISS, ALARM_TIMEOUT}
        case DISMISS_SIG: // intentionally fall through
        case ALARM_TIMEOUT_SIG: {
            status_ = Q_TRAN(&NotificationMgr_idle);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
//$enddef${Components::NotificationMgr} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
