//$file${./active_objects::alarm.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: _watch.qm
// File:  ${./active_objects::alarm.c}
//
// This code has been generated by QM 6.2.3 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// Copyright (c) 2005 Quantum Leaps, LLC
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for licensees
// interested in retaining the proprietary status of the generated code.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${./active_objects::alarm.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpc.h"
#include "bsp.h"
#include "app.h"
#include "rtc.h"

// DECLARA OS MÉTODOS
//$declare${Components::AlarmMgr} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Components::AlarmMgr} ....................................................
typedef struct AlarmMgr {
// protected:
    QActive super;

// private:
    Alarm alarms[MAX_ALARMS];

// public:
} AlarmMgr;

extern AlarmMgr AlarmMgr_inst;

// public:
static void AlarmMgr_reschedule(AlarmMgr * const me);

// protected:
static QState AlarmMgr_initial(AlarmMgr * const me, void const * const par);
static QState AlarmMgr_active(AlarmMgr * const me, QEvt const * const e);
//$enddecl${Components::AlarmMgr} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

// CRIA O OBJETO
//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${App::AO_AlarmMgr} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${App::AO_AlarmMgr} ........................................................
QActive* const AO_AlarmMgr = Q_ACTIVE_UPCAST(&AlarmMgr_inst);
//$enddef${App::AO_AlarmMgr} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define${App::AlarmMgr_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${App::AlarmMgr_ctor} ......................................................
void AlarmMgr_ctor(void) {
    AlarmMgr *me = &AlarmMgr_inst;
    QActive_ctor(&me->super, Q_STATE_CAST(&AlarmMgr_initial));

     for (int i = 0; i < MAX_ALARMS; ++i) {
        me->alarms[i].enabled = false;
    }

    // 2. Cria alarmes de teste (ex: às 08:00 e 12:00 todos os dias)
    me->alarms[0].id = 1;
    me->alarms[0].hour = 12;
    me->alarms[0].minute = 1;
    me->alarms[0].weekday_mask = 0x7F; // 0x7F = todos os 7 dias
    me->alarms[0].medicine_id = 101;
    me->alarms[0].enabled = true;

    me->alarms[1].id = 2;
    me->alarms[1].hour = 12;
    me->alarms[1].minute = 0;
    me->alarms[1].weekday_mask = 0x7F;
    me->alarms[1].medicine_id = 102;
    me->alarms[1].enabled = true;



}
//$enddef${App::AlarmMgr_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

// CRIA OS
//$define${Components::AlarmMgr} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Components::AlarmMgr} ....................................................
AlarmMgr AlarmMgr_inst;

//${Components::AlarmMgr::reschedule} ........................................
static void AlarmMgr_reschedule(AlarmMgr * const me) {
    bsp_datetime_t now;
    bsp_get_time(&now);

    uint32_t now_mins = (uint32_t)now.hour * 60 + now.minute;
    uint8_t current_wday = 7;

    uint32_t shortest_diff = UINT32_MAX;
    Alarm const *next_alarm = NULL;

    for (int i = 0; i < MAX_ALARMS; ++i) {
        if (!me->alarms[i].enabled) {
            continue;
        }

        uint32_t alarm_mins = (uint32_t)me->alarms[i].hour * 60 + me->alarms[i].minute;

        for (uint8_t day_offset = 0; day_offset < 7; ++day_offset) {
            uint8_t target_wday = (current_wday + day_offset) % 7;

            if (me->alarms[i].weekday_mask & (1U << target_wday)) {
                uint32_t diff_mins;

                if (day_offset == 0) {
                    if (alarm_mins > now_mins) {
                        diff_mins = alarm_mins - now_mins;
                    } else {
                        continue;
                    }
                } else {
                    diff_mins = (day_offset * 1440U + alarm_mins) - now_mins;
                }

                if (diff_mins < shortest_diff) {
                    shortest_diff = diff_mins;
                    next_alarm = &me->alarms[i];
                }
                break;
            }
        }
    }

    if (next_alarm != NULL) {
        rtc_set_alarm(next_alarm->hour, next_alarm->minute, 0);
    } else {
        rtc_cancel_alarm();
    }
}

//${Components::AlarmMgr::SM} ................................................
static QState AlarmMgr_initial(AlarmMgr * const me, void const * const par) {
    //${Components::AlarmMgr::SM::initial}
    (void)par;
    QActive_subscribe(&me->super, ADD_ALARM_SIG);
    QActive_subscribe(&me->super, REMOVE_ALARM_SIG);
    QActive_subscribe(&me->super, TOGGLE_ALARM_SIG);
    QActive_subscribe(&me->super, TIME_CHANGED_SIG);
    return Q_TRAN(&AlarmMgr_active);
}

//${Components::AlarmMgr::SM::active} ........................................
static QState AlarmMgr_active(AlarmMgr * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${Components::AlarmMgr::SM::active}
        case Q_ENTRY_SIG: {
            AlarmMgr_reschedule(me);
            status_ = Q_HANDLED();
            break;
        }
        //${Components::AlarmMgr::SM::active::RTC_ALARM}
        case RTC_ALARM_SIG: {
            bsp_datetime_t now;
            bsp_get_time(&now);

            // Avisa quem precisa saber (GuiMgr e NotificationMgr)
            for (int i = 0; i < MAX_ALARMS; ++i) {
                if (me->alarms[i].enabled &&
                    me->alarms[i].hour == now.hour &&
                    me->alarms[i].minute == now.minute) {

                    MedicineAlarmEvt *evt = Q_NEW(MedicineAlarmEvt, MEDICINE_ALARM_SIG);
                    evt->medicine_id = me->alarms[i].medicine_id;
                    QF_PUBLISH(&evt->super, me);
                }
            }
            AlarmMgr_reschedule(me);
            status_ = Q_HANDLED();
            break;
        }
        //${Components::AlarmMgr::SM::active::ADD_ALARM, REMOVE_ALARM, TOGGLE_~}
        case ADD_ALARM_SIG: // intentionally fall through
        case REMOVE_ALARM_SIG: // intentionally fall through
        case TOGGLE_ALARM_SIG: // intentionally fall through
        case TIME_CHANGED_SIG: {
            AlarmMgr_reschedule(me);
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
//$enddef${Components::AlarmMgr} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
