//$file${./active_objects::gui.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: _watch.qm
// File:  ${./active_objects::gui.c}
//
// This code has been generated by QM 6.2.3 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// Copyright (c) 2005 Quantum Leaps, LLC
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for licensees
// interested in retaining the proprietary status of the generated code.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${./active_objects::gui.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpc.h"
#include "bsp.h"
#include "app.h"
#include "ui_manager.h"

// DECLARA OS MÉTODOS
//$declare${Components::GuiMgr} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Components::GuiMgr} ......................................................
typedef struct GuiMgr {
// protected:
    QActive super;

// private:
    QTimeEvt timeEvt0;

// public:

// private:
    uint8_t hour;
    uint8_t minute;
    uint8_t second;
    uint8_t curr_mode;

// public:
    uint8_t time_format;

// private:
    QStateHandler history_active;

// private state histories
    QStateHandler hist_active;
} GuiMgr;

extern GuiMgr GuiMgr_inst;

// protected:
static QState GuiMgr_initial(GuiMgr * const me, void const * const par);
static QState GuiMgr_active(GuiMgr * const me, QEvt const * const e);
static QState GuiMgr_timekeeping(GuiMgr * const me, QEvt const * const e);
// SHOWS FACE
static QState GuiMgr_countdown_FACE(GuiMgr * const me, QEvt const * const e);
// SHOWS CONFIG
static QState GuiMgr_countdown_config(GuiMgr * const me, QEvt const * const e);
// SHOWS FACE
static QState GuiMgr_time_date_FACE(GuiMgr * const me, QEvt const * const e);
// SHOWS CONFIG
static QState GuiMgr_time_date_config(GuiMgr * const me, QEvt const * const e);
static QState GuiMgr_accel(GuiMgr * const me, QEvt const * const e);
// SHOWS FACE
static QState GuiMgr_settings_FACE(GuiMgr * const me, QEvt const * const e);
// SHOW SETTINGS
static QState GuiMgr_settings(GuiMgr * const me, QEvt const * const e);
static QState GuiMgr_medicine_popup(GuiMgr * const me, QEvt const * const e);
//$enddecl${Components::GuiMgr} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

// CRIA O OBJETO
//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${App::AO_GuiMgr} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${App::AO_GuiMgr} ..........................................................
QActive* const AO_GuiMgr = Q_ACTIVE_UPCAST(&GuiMgr_inst);
//$enddef${App::AO_GuiMgr} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define${App::GuiMgr_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${App::GuiMgr_ctor} ........................................................
void GuiMgr_ctor(void) {
    GuiMgr *me = &GuiMgr_inst;
    QActive_ctor(&me->super, Q_STATE_CAST(&GuiMgr_initial));
    QTimeEvt_ctorX(&me->timeEvt0, &me->super, TICK_SIG, 0U);
}
//$enddef${App::GuiMgr_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

// CRIA OS
//$define${Components::GuiMgr} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Components::GuiMgr} ......................................................
GuiMgr GuiMgr_inst;

//${Components::GuiMgr::SM} ..................................................
static QState GuiMgr_initial(GuiMgr * const me, void const * const par) {
    //${Components::GuiMgr::SM::initial}
    (void)par; // unused parameter
    QActive_subscribe(&me->super, ENTER_SIG);
    QActive_subscribe(&me->super, MODE_SIG);
    QActive_subscribe(&me->super, BACK_SIG);
    QActive_subscribe(&me->super, TOGGLE_SIG);
    QActive_subscribe(&me->super, MEDICINE_ALARM_SIG);
    // state history attributes
    me->hist_active = Q_STATE_CAST(&GuiMgr_timekeeping);
    return Q_TRAN(&GuiMgr_active);
}

//${Components::GuiMgr::SM::active} ..........................................
static QState GuiMgr_active(GuiMgr * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${Components::GuiMgr::SM::active}
        case Q_EXIT_SIG: {
            // save deep history
            me->hist_active = QHsm_state(Q_HSM_UPCAST(me));
            status_ = Q_HANDLED();
            break;
        }
        //${Components::GuiMgr::SM::active::initial}
        case Q_INIT_SIG: {
            status_ = Q_TRAN(&GuiMgr_timekeeping);
            break;
        }
        //${Components::GuiMgr::SM::active::MEDICINE_ALARM}
        case MEDICINE_ALARM_SIG: {
            status_ = Q_TRAN(&GuiMgr_medicine_popup);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${Components::GuiMgr::SM::active::timekeeping} .............................
static QState GuiMgr_timekeeping(GuiMgr * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${Components::GuiMgr::SM::active::timekeeping}
        case Q_ENTRY_SIG: {
            QTimeEvt_disarm(&me->timeEvt0);
            QTimeEvt_armX(&me->timeEvt0, 1000U, 100U);

            char buf[10];
            bsp_datetime_t dt;
            bsp_get_time(&dt);

            ui_manager_update_time(dt.hour, dt.minute, dt.second);
            ui_manager_show_watchface();
            //bsp_display_write_string_ssd1306(0, 5, "entry->timekeeping");
            status_ = Q_HANDLED();
            break;
        }
        //${Components::GuiMgr::SM::active::timekeeping::MODE}
        case MODE_SIG: {
            bsp_display_clear_ssd1306();
            status_ = Q_TRAN(&GuiMgr_countdown_FACE);
            break;
        }
        //${Components::GuiMgr::SM::active::timekeeping::TICK}
        case TICK_SIG: {
            // ATUALIZA O TEMPO

            char buf[10];
            bsp_datetime_t dt;
            bsp_get_time(&dt);

            ui_manager_update_time(dt.hour, dt.minute, dt.second);
            //snprintf(buf, sizeof(buf), "%02d:%02d:%02d", dt.hour, dt.minute, dt.second);
            //bsp_display_write_string_ssd1306(30, 25, buf);
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&GuiMgr_active);
            break;
        }
    }
    return status_;
}

//${Components::GuiMgr::SM::active::countdown_FACE} ..........................
static QState GuiMgr_countdown_FACE(GuiMgr * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${Components::GuiMgr::SM::active::countdown_FACE}
        case Q_ENTRY_SIG: {
            ui_manager_show_countdown();
            status_ = Q_HANDLED();
            break;
        }
        //${Components::GuiMgr::SM::active::countdown_FACE::TOGGLE}
        case TOGGLE_SIG: {
            // STARTA OU PARA O CRONOMETRO
            status_ = Q_HANDLED();
            break;
        }
        //${Components::GuiMgr::SM::active::countdown_FACE::ENTER}
        case ENTER_SIG: {
            status_ = Q_TRAN(&GuiMgr_countdown_config);
            break;
        }
        //${Components::GuiMgr::SM::active::countdown_FACE::MODE}
        case MODE_SIG: {
            bsp_display_clear_ssd1306();
            status_ = Q_TRAN(&GuiMgr_accel);
            break;
        }
        //${Components::GuiMgr::SM::active::countdown_FACE::TIMEOUT}
        case TIMEOUT_SIG: {
            status_ = Q_TRAN(&GuiMgr_timekeeping);
            break;
        }
        default: {
            status_ = Q_SUPER(&GuiMgr_active);
            break;
        }
    }
    return status_;
}

//${Components::GuiMgr::SM::active::countdown_FACE::countdown_config} ........
static QState GuiMgr_countdown_config(GuiMgr * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${Components::GuiMgr::SM::active::countdown_FACE::countdown_config}
        case Q_ENTRY_SIG: {
            //blink(me->time[sel_field])
            bsp_display_write_string_ssd1306(0, 5, "entry->countdown_conf");
            status_ = Q_HANDLED();
            break;
        }
        //${Components::GuiMgr::SM::active::countdown_FACE::countdown_config::MODE}
        case MODE_SIG: {
            // AFIRMA E AVANÇA CAMPO
            bsp_display_clear_ssd1306();
            bsp_display_write_string_ssd1306(5, 5, "cd_conf->mode++");
            status_ = Q_HANDLED();
            break;
        }
        //${Components::GuiMgr::SM::active::countdown_FACE::countdown_config::TOGGLE}
        case TOGGLE_SIG: {
            // AUMENTA +1 O VALOR DO CAMPO HORA, MINUTO OU SEGUNDO

            // OBS -> DEFINIDO PELA VARIÁVEL DE CONTROLE DE MODE.
            status_ = Q_HANDLED();
            break;
        }
        //${Components::GuiMgr::SM::active::countdown_FACE::countdown_config::ENTER}
        case ENTER_SIG: {
            bsp_display_clear_ssd1306();
            bsp_display_write_string_ssd1306(0, 5, "entry->countdown_face");
            status_ = Q_TRAN(&GuiMgr_countdown_FACE);
            break;
        }
        default: {
            status_ = Q_SUPER(&GuiMgr_countdown_FACE);
            break;
        }
    }
    return status_;
}

//${Components::GuiMgr::SM::active::time_date_FACE} ..........................
static QState GuiMgr_time_date_FACE(GuiMgr * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${Components::GuiMgr::SM::active::time_date_FACE}
        case Q_ENTRY_SIG: {
            bsp_display_write_string_ssd1306(0, 5, "entry->timedate_face");
            status_ = Q_HANDLED();
            break;
        }
        //${Components::GuiMgr::SM::active::time_date_FACE::ENTER}
        case ENTER_SIG: {
            status_ = Q_TRAN(&GuiMgr_time_date_config);
            break;
        }
        //${Components::GuiMgr::SM::active::time_date_FACE::MODE}
        case MODE_SIG: {
            bsp_display_clear_ssd1306();
            status_ = Q_TRAN(&GuiMgr_settings_FACE);
            break;
        }
        //${Components::GuiMgr::SM::active::time_date_FACE::TIMEOUT}
        case TIMEOUT_SIG: {
            status_ = Q_TRAN(&GuiMgr_timekeeping);
            break;
        }
        default: {
            status_ = Q_SUPER(&GuiMgr_active);
            break;
        }
    }
    return status_;
}

//${Components::GuiMgr::SM::active::time_date_FACE::time_date_config} ........
static QState GuiMgr_time_date_config(GuiMgr * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${Components::GuiMgr::SM::active::time_date_FACE::time_date_config}
        case Q_ENTRY_SIG: {
            bsp_display_write_string_ssd1306(0, 5, "entry->time_date_conf");

            char buf[10];
            bsp_datetime_t dt;
            bsp_get_time(&dt);

            me->hour = dt.hour;
            me->minute = dt.minute;
            me->second = dt.second;
            //me->time_format = dt.time_format;
            me->curr_mode = 0;

            snprintf(buf, sizeof(buf), "%02d:%02d:%02d", me->hour, me->minute, me->second);
            bsp_display_write_string_ssd1306(30, 28, buf);
            status_ = Q_HANDLED();
            break;
        }
        //${Components::GuiMgr::SM::active::time_date_FACE::time_date_config::MODE}
        case MODE_SIG: {
            me->curr_mode = (me->curr_mode + 1) % 3;
            status_ = Q_HANDLED();
            break;
        }
        //${Components::GuiMgr::SM::active::time_date_FACE::time_date_config::TOGGLE}
        case TOGGLE_SIG: {
            switch(me->curr_mode) {
                case 0:
                    me->hour = (me->hour < 23) ? me->hour + 1 : 0;
                    break;
                case 1:
                    me->minute = (me->minute < 59) ? me->minute + 1 : 0;
                    break;
                case 2:
                    me->second = (me->second < 59) ? me->second += 1 : 0;
                case 3:
                    me->time_format = !me->time_format;
            }
            char buf[10];
            //if (me->time_format == 0) // 12h
            //    snprintf(buf, sizeof(buf), "%02d:%02d:%02d 12h", me->hour, me->minute, me->second);
            //else
            //  snprintf(buf, sizeof(buf), "%02d:%02d:%02d 24h", me->hour, me->minute, me->second);
            snprintf(buf, sizeof(buf), "%02d:%02d:%02d", me->hour, me->minute, me->second);

            bsp_display_write_string_ssd1306(30, 28, buf);
            status_ = Q_HANDLED();
            break;
        }
        //${Components::GuiMgr::SM::active::time_date_FACE::time_date_config::ENTER}
        case ENTER_SIG: {
            bsp_display_clear_ssd1306();
            bsp_display_write_string_ssd1306(0, 5, "entry->timedate_face");
            bsp_datetime_t dt;
            dt.hour = me->hour;
            dt.minute = me->minute;
            dt.second = me->second;
            //dt.time_format = me->time_format;

            bsp_set_time(&dt);
            status_ = Q_TRAN(&GuiMgr_time_date_FACE);
            break;
        }
        default: {
            status_ = Q_SUPER(&GuiMgr_time_date_FACE);
            break;
        }
    }
    return status_;
}

//${Components::GuiMgr::SM::active::accel} ...................................
static QState GuiMgr_accel(GuiMgr * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${Components::GuiMgr::SM::active::accel}
        case Q_ENTRY_SIG: {
            QTimeEvt_disarm(&me->timeEvt0);
            QTimeEvt_armX(&me->timeEvt0, 50U, 100U);
            bsp_display_write_string_ssd1306(0, 5, "entry->accel");
            status_ = Q_HANDLED();
            break;
        }
        //${Components::GuiMgr::SM::active::accel::MODE}
        case MODE_SIG: {
            bsp_display_clear_ssd1306();
            status_ = Q_TRAN(&GuiMgr_time_date_FACE);
            break;
        }
        //${Components::GuiMgr::SM::active::accel::TIMEOUT}
        case TIMEOUT_SIG: {
            status_ = Q_TRAN(&GuiMgr_timekeeping);
            break;
        }
        //${Components::GuiMgr::SM::active::accel::TICK}
        case TICK_SIG: {
            bsp_accel_raw_t accel;
            char buf[32];
            if (bsp_accel_get_xyz(&accel) == 0) {
                snprintf(buf, sizeof(buf), "X:%d Y:%d Z:%d", accel.x, accel.y, accel.z);
            //    snprintf(buf, sizeof(buf), "Z:%d", accel.z);
                bsp_display_write_string_ssd1306(0, 40, buf);
            }
            //snprintf(buf, sizeof(buf), "deu erro");

            bsp_display_write_string_ssd1306(0, 40, buf);
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&GuiMgr_active);
            break;
        }
    }
    return status_;
}

//${Components::GuiMgr::SM::active::settings_FACE} ...........................
static QState GuiMgr_settings_FACE(GuiMgr * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${Components::GuiMgr::SM::active::settings_FACE}
        case Q_ENTRY_SIG: {
            bsp_display_write_string_ssd1306(0, 5, "entry->settings_face");
            status_ = Q_HANDLED();
            break;
        }
        //${Components::GuiMgr::SM::active::settings_FACE::ENTER}
        case ENTER_SIG: {
            status_ = Q_TRAN(&GuiMgr_settings);
            break;
        }
        //${Components::GuiMgr::SM::active::settings_FACE::MODE}
        case MODE_SIG: {
            bsp_display_clear_ssd1306();
            status_ = Q_TRAN(&GuiMgr_timekeeping);
            break;
        }
        //${Components::GuiMgr::SM::active::settings_FACE::TIMEOUT}
        case TIMEOUT_SIG: {
            bsp_display_clear_ssd1306();
            status_ = Q_TRAN(&GuiMgr_timekeeping);
            break;
        }
        default: {
            status_ = Q_SUPER(&GuiMgr_active);
            break;
        }
    }
    return status_;
}

//${Components::GuiMgr::SM::active::settings_FACE::settings} .................
static QState GuiMgr_settings(GuiMgr * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${Components::GuiMgr::SM::active::settings_FACE::settings}
        case Q_ENTRY_SIG: {
            bsp_display_write_string_ssd1306(0, 5, "entry->settings_conf");
            status_ = Q_HANDLED();
            break;
        }
        //${Components::GuiMgr::SM::active::settings_FACE::settings::ENTER}
        case ENTER_SIG: {
            status_ = Q_TRAN(&GuiMgr_settings_FACE);
            break;
        }
        //${Components::GuiMgr::SM::active::settings_FACE::settings::TOGGLE}
        case TOGGLE_SIG: {
            status_ = Q_HANDLED();
            break;
        }
        //${Components::GuiMgr::SM::active::settings_FACE::settings::MODE}
        case MODE_SIG: {
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&GuiMgr_settings_FACE);
            break;
        }
    }
    return status_;
}

//${Components::GuiMgr::SM::medicine_popup} ..................................
static QState GuiMgr_medicine_popup(GuiMgr * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${Components::GuiMgr::SM::medicine_popup}
        case Q_ENTRY_SIG: {
            ui_manager_set_alarm_text("TOMAR REMEDIO!");
            ui_manager_show_alarm();
            QTimeEvt_disarm(&me->timeEvt0);
            QTimeEvt_armX(&me->timeEvt0, 5000U, 0U);
            //bsp_display_clear_ssd1306();
            //bsp_display_write_string_ssd1306(0, 10, "TOMAR REMEDIO!");
            //bsp_display_write_string_ssd1306(0, 30, "ENTER:OK  MODE:SONECA");
            status_ = Q_HANDLED();
            break;
        }
        //${Components::GuiMgr::SM::medicine_popup}
        case Q_EXIT_SIG: {
            QTimeEvt_disarm(&me->timeEvt0);
            status_ = Q_HANDLED();
            break;
        }
        //${Components::GuiMgr::SM::medicine_popup::ENTER, MODE, TICK}
        case ENTER_SIG: // intentionally fall through
        case MODE_SIG: // intentionally fall through
        case TICK_SIG: {
            static const QEvt dismissEvt = { DISMISS_SIG, 0U, 0U };
            QF_PUBLISH(&dismissEvt, me);
            status_ = Q_TRAN_HIST(me->hist_active);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
//$enddef${Components::GuiMgr} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
